### ISSUE TITLE
Component not working after update to 100.1

### ISSUE THREAD

**Issue by KosmixLB** [fwestenberg/reolink#4]
I really enjoyed your custom component, but it seems broke after updating to home assistant 100.1.  This is what the log says:
`Platform error: camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 778, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/reolink/camera.py", line 13, in <module>
    from homeassistant.util.async_ import run_coroutine_threadsafe
ImportError: cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' (/usr/src/homeassistant/homeassistant/util/async_.py)`

**Comment by KosmixLB** [comment]
Have a fix for it. 

In camera.py remove:

`from homeassistant.util.async_ import run_coroutine_threadsafe`

Change:
`return run_coroutine_threadsafe(`
Into:
`return asyncio.run_coroutine_threadsafe(`
